// User Login
const SET_AUTH = 'SET_AUTH';
const DELETE_AUTH = 'DELETE_AUTH';
const CREATE_USER = 'CREATE_USER';

// Tags
const SET_TAGS = 'SET_TAGS';
const CREATE_TAG = 'CREATE_TAG';
const DELETE_TAG = 'DELETE_TAG';
const UPDATE_TAG = 'UPDATE_TAG';


// Brands
const SET_BRANDS = 'SET_BRANDS';
const CREATE_BRAND = 'CREATE_BRAND';
const DELETE_BRAND = 'DELETE_BRAND';
const UPDATE_BRAND = 'UPDATE_BRAND';


export {
  SET_AUTH,
  DELETE_AUTH,
  CREATE_USER,
  SET_TAGS,
  CREATE_TAG,
  DELETE_TAG,
  UPDATE_TAG,
  SET_BRANDS,
  CREATE_BRAND,
  DELETE_BRAND,
  UPDATE_BRAND,
};
